# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch: "1 day"
      semver-minor: "7 days"
      semver-major: "7 days"
    labels:
      - "github-actions"
      - "dependencies"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/api" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch: "1 day"
      semver-minor: "7 days"
      semver-major: "7 days"
    labels:
      - "api"
      - "dependencies"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/client" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch: "1 day"
      semver-minor: "7 days"
      semver-major: "7 days"
    labels:
      - "ui"
      - "dependencies"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/models" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch: "1 day"
      semver-minor: "7 days"
      semver-major: "7 days"
    labels:
      - "models"
      - "dependencies"
