# See https://github.com/actions/labeler

'🚨 action':
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'
  - head-branch: ['action']

api:
  - changed-files:
    - any-glob-to-any-file: 'packages/api/**'

ui:
  - changed-files:
    - any-glob-to-any-file: 'packages/client/**'

models:
  - changed-files:
    - any-glob-to-any-file: 'packages/models/**'

project:
  - changed-files:
    - all-glob-to-any-file: ['¡.github/workflows/**','!packages/api/**', '!packages/client/**','!packages/models/**']
  
