# See https://github.com/actions/labeler

'🚨 action':
  - .github/workflows/**

api:
  - any: ['packages/api/**']

ui:
  - any: ['packages/client/**']

models:
  - any: ['packages/models/**']

project:
  - all: ['¡.github/workflows/**','!packages/api/**', '!packages/client/**','!packages/models/**']