services:
  mongo-snapshots:
    image: mongo:4.4.30
    container_name: finper-mongo-snapshots
    ports:
      - "27018:27017"
    volumes:
      - mongo-snapshots-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: finper-snapshots
    restart: unless-stopped

volumes:
  mongo-snapshots-data:
