packages:
  - scripts/*
  - packages/api
  - packages/bot
  - packages/client
  - packages/db
  - packages/types

ignoredBuiltDependencies:
  - '@swc/core'
  - msw
  - pre-push
  - protobufjs
  - spawn-sync
  - unrs-resolver

onlyBuiltDependencies:
  - bcrypt
  - better-sqlite3
  - esbuild

overrides:
  '@types/express-serve-static-core': 5.1.0
