services:
  - name: $CI_REGISTRY/fintonic-ops/docker/docker-dind-fintonic:latest
    alias: docker

include:
- https://gitlab.fintonic.com/fintonic-ops/gitlab-ci-includes/raw/master/insurances/deploy-node-dev.yml
- https://gitlab.fintonic.com/fintonic-ops/gitlab-ci-includes/raw/master/insurances/deploy-node-pre-pro-es.yml

variables:
  AWS_REGISTRY_IMAGE: 646771319519.dkr.ecr.eu-west-1.amazonaws.com/insurance-public-api
  DOCKER_TEST_IMAGE: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG
  DOCKER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_RELEASE_IMAGE: $AWS_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHA
  K8S_IMAGE_NAME: insurance_public_api

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - eval `aws ecr get-login --region eu-west-1 --no-include-email`

stages:
  - test
  - build
  - release
  - deploy

test:
  stage: test
  script:
  - docker build --pull --build-arg CI_COMMIT_REF=$CI_COMMIT_REF_NAME --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA --build-arg NPM_INSTALL_CMD="npm install" -f Dockerfile-test -t $DOCKER_TEST_IMAGE .
  - docker run --rm $DOCKER_TEST_IMAGE test

build:
  stage: build
  script:
  - docker build --pull --build-arg CI_COMMIT_REF=$CI_COMMIT_REF_NAME --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA --build-arg NPM_INSTALL_CMD="npm install --production" -t $DOCKER_BUILD_IMAGE .
  - docker push $DOCKER_BUILD_IMAGE
  only:
  - master

build-pre:
  stage: build
  script:
  - docker build --pull --build-arg CI_COMMIT_REF=$CI_COMMIT_REF_NAME --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA --build-arg NPM_INSTALL_CMD="npm install --production" -f Dockerfile-pre -t $DOCKER_BUILD_IMAGE .
  - docker push $DOCKER_BUILD_IMAGE
  except:
  - master

release-image:
  stage: release
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
  - promote_docker.sh $DOCKER_BUILD_IMAGE $DOCKER_RELEASE_IMAGE