version: "3"
services:
  api:
    container_name: api
    build:
      context: "."
      args:
        GITLAB_REGISTRY_TOKEN: ""
        MONGODB_USER: ""
        MONGODB_PASS: ""
        JWT_SECRET: ""
        SALT_ROUNDS: 12
        GRAFANA_LOGGER_USER: 1
        GRAFANA_LOGGER_PASSWORD: ""
    ports :
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules