export const ACCOUNTS = 'accounts'
export const CATEGORIES = 'categories'
export const GROUPED_CATEGORIES = 'categories/grouped'
export const TRANSACTIONS = 'transactions'
export const STORES = 'stores'
