# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm i --workspace=@soker90/finper-api
      - name: Lint
        run: make lint-api

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm i --workspace=@soker90/finper-api
      - name: Build
        run: make build-api

  test:
    needs: [ lint, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm i --workspace=@soker90/finper-api
      - name: Test
        run: make test-api
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: api
