name: Docker build

on:
  push:
    branches:
      - 'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/finper:daily
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/finper:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/finper:buildcache,mode=max

