name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: soker90/finper-client:latest
          context: ./packages/client
          file: ./packages/client/Dockerfile
          build-args: API_HOST=${{ secrets.API_HOST }}
      
      - name: Build and push api
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: soker90/finper-api:latest
          context: ./packages/api
          file: ./packages/api/Dockerfile
