name: DockerHub deploy
on:
  push:
    branches:
      - 'master'

jobs:
    Backend-Deployment:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./packages/api
            file: ./packages/api/Dockerfile
            push: true
            tags: soker90/finper-api:daily
