name: Docker build

on:
  push:
    branches:
      - 'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: ls
          run: ls -a
        - name: Build the tagged Docker image
          run: docker build ./packages/api --file packages/api/Dockerfile --tag soker90/finper-api:daily
        - name: Push the tagged Docker image
          run: docker push soker90/finper-api:daily
        - name: Build the latest Docker image
          run: docker build ./packages/api --file packages/api/Dockerfile --tag soker90/finper-api:latest
        - name: Push the latest Docker image
          run: docker push soker90/finper-api:latest

